SEARCH_FIELD = 'xpath://*[@class="search"]//input'
SUBMIT_BTN = 'xpath://*[@class="search"]/button'
DROPDOWN_MENU = 'xpath://*[@class="search-dropdown-menu"]'
LOADING_COVER = 'xpath://*[@aria-label="Loading"]'
ERROR_MSG_LOC = 'xpath://*[@class="sub not-found notFoundOpen"]'
CITY_NAME_CONTENT = 'xpath://*[@class="section-content"]//h2'
CITY_TEMPERATURE_CONTENT = 'xpath://*[@class="nowrap horizontal"]/span'
FEELS_LIKE_TEMPERATURE = 'xpath://*[@class="nowrap horizontal"]/following-sibling::div/span'
IMPERIAL_BTN = 'xpath://*[@class="widget-switch switch-blue"]//*[@for="imperial"]'
WEATHER_ITEMS = 'xpath://*[contains(@class,"weather-items")]//li'

